obstacles:
  config_path: 'config/obstacles.json'

move_l:
  speed: 0.05

  resolution_m: 0.005
  min_resolution_m_offset: -0.005
  max_resolution_m_offset: 0.005

  jump_threshold: 2.0
  min_jump_threshold_offset: -2.0
  max_jump_threshold_offset: 2.0

move_j:
  speed: 0.05  # todo: set it. With `set_max_velocity_scaling_factor()`?

open_gripper:
  width: 0.08
  speed: 0.4

close_gripper:
  # todo: compare with https://github.com/frankaemika/franka_ros/issues/256
  # goal.width = 0.022
  # goal.epsilon.inner = 0.005
  # goal.epsilon.outer = 0.005
  # goal.speed = 0.1
  # goal.force = 5
  width: 0.05
  epsilon_inner: 0.01
  epsilon_outer: 0.01
  speed: 0.1
  force: 20
